export const MOCK_ORGS = [
    {
        id: "1",
        name: "Tech for Good",
        description: "Leveraging technology to solve social issues",
        imageUrl: "https://placecats.com/300/200",
        mission: "Our mission is to harness the power of technology to address pressing social challenges and improve lives.",
        founded: "2015",
        location: "San Francisco, CA",
        website: "https://techforgood.org",
        contactEmail: "info@techforgood.org",
    },
    {
        id: "2",
        name: "Green Earth Initiative",
        description: "Promoting sustainable practices for a greener planet",
        imageUrl: "https://placecats.com/300/200",
        mission: "We strive to create a sustainable future by promoting eco-friendly practices and environmental conservation.",
        founded: "2010",
        location: "Portland, OR",
        website: "https://greenearthinitiative.org",
        contactEmail: "contact@greenearthinitiative.org",
    },
    {
        id: "3",
        name: "Education for All",
        description: "Providing quality education to underprivileged communities",
        imageUrl: "https://placecats.com/300/200",
        mission: "We believe that education is the key to unlocking the potential of every child and creating a brighter future for all.",
        founded: "2010",
        location: "San Francisco, CA",
        website: "https://educationforall.org",
        contactEmail: "info@educationforall.org",
    },
    {
        id: "4",
        name: "Health First",
        description: "Improving healthcare access in remote areas",
        imageUrl: "https://placecats.com/300/200",
        mission: "We believe that healthcare is a fundamental right and that everyone should have access to quality, affordable healthcare.",
        founded: "2010",
        location: "San Francisco, CA",
        website: "https://healthfirst.org",
        contactEmail: "info@healthfirst.org"

    },
]